# Add 'traslations-es' to any change in /src/pages/ folder or subfolders except for EN files
translations:
  - any: ['src/pages/**/*', '!src/pages/en/**/*']

documentation:
  - any: ['src/pages/en/**/*.md']

dependencies:
  - 'package.json'

navigation:
  - 'src/navigation.yaml'